tables:
  - {
    name: Kitty!,
    rows: [A, B],
    tables_per_row: 5,
    seats_per_table: 2,
    left_end_table: true,
    right_end_table: true
    }
  - {
    name: Shiny,
    rows: [A, B],
    tables_per_row: 6,
    seats_per_table: 2
    }
